django_official/urls.py
from django.contrib import admin
from django.urls import path, include
from poll import urls

urlpatterns = [
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'poll'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
]

poll/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.TextField(max_length=200)
    pub_date = models.DateTimeField(timezone.now)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.TextField(max_length=200)
    choice_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_vote = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic

# Create your views here.
''' def index(request):
    try:
        recent_questions = Question.objects.order_by('pub_date')[:5]
        context = {'recent_questions': recent_questions}
    except IndexError:
        return Http404 
    return render(request, 'poll/index.html', context)'''

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'recent_questions'

    def get_queryset(self):
        return Question.objects.order_by('pub_date')[:5]


''' def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}

    return render(request, 'poll/detail.html', context) '''

class DetailView(generic.DetailView):
    model=Question
    template_name = 'poll/detail.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError or Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {'question': question, 'error_message': "You didn't select a choice"})

    else:
        selected_choice.choice_vote+=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

''' def results(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question} 
    return render(request, 'poll/results.html', context)'''

class ResultView(generic.DetailView):
    model=Question
    template_name = 'poll/results.html'

    
    
    

poll/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Page</title>
</head>
<body>

    <h1>{{question.id}}. {{question.question_text}}</h1>
    {% if error_message %}<strong><p>{{error_message}}</p></strong> {% endif %}
    <form action="{% url 'poll:vote' question.id %}" method='post'> 
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br>
        {% endfor %}
        <input type="submit" value='vote'>
    </form>

</body>
</html>

poll/templates/poll/index.html
{% load static %}

<link rel="stylesheet" type='text/css' href="{% static 'poll/stylesheet.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page</title>
</head>
<body>
    {% if recent_questions %}
        {% for question in recent_questions %}
            <ul>
                <li><a href="{% url 'poll:detail' question.id %}">Question {{question.id}}</a></li>
            </ul>
        {% endfor %}
    {% endif %}
</body>
</html>

poll/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.choice_vote }} vote{{ choice.choice_vote|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'poll:detail' question.id %}">Vote again?</a>
</body>
</html>